### ISSUE TITLE
how to save as picture either or xml

### ISSUE THREAD

**Issue by ziyuwzf** [lquirosd/P2PaLA#10]

**Comment by lquirosd** [comment]
PAGE complaint XML file is saved by default in <work_dir>/results/<test,val,prod>/page/, to visualize the results I recommend [Traskribus](https://transkribus.eu/Transkribus/) or [nw-page-editor](https://github.com/mauvilsa/nw-page-editor). Please see [USAGE](https://github.com/lquirosd/P2PaLA#usage) section on main README file, point 4.

**Comment by ziyuwzf** [comment]
how to save as picture？can you give me some advice？

**Comment by lquirosd** [comment]
Since document layout could be very complex I don't recommend to save it as a picture directly, but if you want just for baselines there is a script [drawBaselines](https://github.com/PRHLT/BaseLinePage/blob/master/SRC/drawBaselines.cc) you can compile stand alone using `g++ -o drawBaselines drawBaselines.cc -lopencv_imgproc -lopencv_core  -lopencv_highgui -lpugixml` ( libpugixml and opencv must be available in your system `sudo apt-get install libpugixml-dev libopencv-dev`)

**Comment by longwall** [comment]
Thanks for your comment!
In fact I understood zero-size unix symlinks on Windows  last night..
I managed to visualize the resulting contours with the simple modification of  gen_page() .

Added inside the l_cont loop 

`cv2.drawContours(out_img, [l_cnt], 0, (0, 0, 255), 3)`

I commented out creating the symlinks and added after .save_page() 

`        cv2.imwrite(os.path.realpath( os.path.join(out_folder, img_name)), out_img)`

That demonstrates red polygons around htr lines and it's quite enough for my purposes.
By the way  - do you plan to publish any other models except ALAR?  
Would be interesting to see.
In many cases the actual model can't recognise close verrtically adjacent lines.
